### ISSUE TITLE
plugin import

### ISSUE THREAD

**Issue by temp3l** [MurhafSousli/ng2-wp-api#1]
hi, 
please help on setting up the plugin
I am trying with angular2-webpack-starter/

```
npm i  ng2-wp-api -s

in app.module.ts:
import { WORDPRESS_PROVIDERS, WpState } from 'ng2-wp-api';

@Component({
    selector: 'app',
    providers:[WORDPRESS_PROVIDERS],
    ...
})
export class App {
    constructor(wpState: WpState){
        wpState.setBaseUrl("http://yourWordPressSite.com");
    }
}
```

I always end up with:
 **Cannot find name 'WpState'.**

**Comment by MurhafSousli** [comment]
Hi @stephanMettler, I have just released a new version which is rewritten from scratch, I have also updated the documentation and the example, reinstall the plugin again.

Assuming that you are using the final release of angular 2, import`WordPressModule` in your `app.module` file

``` javascript
import { WordPressModule } from 'ng2-wp-api/dist';

@NgModule({
imports: [
    WordPressModule
  ]
})
```

See [Initializing example](https://github.com/MurhafSousli/ng2-wp-api/blob/master/examples/Initilizing%20WP%20Service.ts)
