### ISSUE TITLE
node_modules/ng2-wp-api/index has no exported member 'WpModel'.

### ISSUE THREAD

**Issue by markgoho** [MurhafSousli/ng2-wp-api#10]
In your model example, I'm importing WpModel but tslint gives me the error above.

**Comment by MurhafSousli** [comment]
hi @markgoho, there is no such export called `WpModel`!

**Comment by markgoho** [comment]
Gotchya! https://github.com/MurhafSousli/ng2-wp-api/blob/master/examples/Model%20using%20the%20service.ts shows importing WpModel....should that actually be WpService?

**Comment by MurhafSousli** [comment]
@markgoho opps, after I updated the example, I forgot to remove it, but as you see it was never used

**Comment by markgoho** [comment]
Okay, thank you for that explanation. I'm fairly new to this whole Angular 2 thing, but I could tell that that import wasn't used, but WpService was.
