### ISSUE TITLE
Allow getBySlug for posts collection

### ISSUE THREAD

**Issue by markgoho** [MurhafSousli/ng2-wp-api#11]
Could you add a method called getBySlug that would take in a slug: string for getting a post by slug rather than id?

**Comment by markgoho** [comment]
I submitted a pull request to add this in. Hopefully it's up to standards!

**Comment by MurhafSousli** [comment]
@markgoho This is already possible using the collection service! but not a bad idea

**Comment by markgoho** [comment]
Forgive me @MurhafSousli 👍

I will research this out further. Could you give an idea of what the call would look like?

.posts().get(????)

**Comment by MurhafSousli** [comment]
@markgoho 
```javascript
this.wpService.collection().posts().get({ slug: "Hello World" })
   .subscribe((res: CollectionResponse) => {
        this.post = res.data[0];
   });
```

**Comment by markgoho** [comment]
You're amazing! I can't for the life of me figure out where in the src or docs it says the .get() method accepts anything except an (id: number). Am I missing a huge part of this?

**Comment by MurhafSousli** [comment]
@markgoho In the doc, I tried to explain the structure, 
**CollectionService** is meant for requesting by args and **ModelService** is meant for requesting by Id (args in *ModelService* would only be useful for enabling `_embed`)
```
    ├── collection()
    |    ├── endpoint(ep)
    |        ├── get(args?)                ** Get Collection by args.
    |        ├── more()                    ** Get Next page collection combined with any previous ones.
    |        ├── next()                    ** Get Next page collection.
    |        ├── prev()                    ** Get Prev page collection.
    |
    ├── model()
    |    ├── endpoint(ep)
    |        ├──  get(id, args?)           ** Get Model by Id.
    |        ├──  add(body)                ** Add Model to WP.
    |        ├──  update(id, body)         ** Update Model by Id.
    |        ├──  delete(id)               ** Delete Model by Id.
```

**Comment by markgoho** [comment]
So, collection() can be used to return one of something, but if any other operations need to be performed (add, update, delete) you have to use model() with an id.

**Comment by MurhafSousli** [comment]
@markgoho no, _collection()_ is meant to get an **array of posts**, but when you use the slug, probably you are looking for the first index `res.data[0]`, in _model()_ it's just `res.data`

In web application it's more reliable to get a single post by ID, rather than the slug, let's say in your app the URL is `www.example.com/posts/hello-world` and this URL got shared on the web, later you renamed your post! now everyone who uses the previous link will get 404.
but if you use the ID, it will always point to the correct post.

Ofcourse WordPress works differently because it runs on the server and it can handle the changes. but it's up to how you like to use it

**Comment by markgoho** [comment]
Thanks for that explanation. Yes, it is much safer to get the post by id -- I've done a bit of WordPress development, and that issue is brought up there as well. Displaying posts by slug is risky for the reason you mentioned.

As a side note here, I'm trying to recreate an existing Wordpress site using your library. My goal is to keep all the URLs the same so that no SEO value is lost when relaunching the site. If I structured things as /post/345 instead of /post/post-title I'd lose a lot....and I'd rather not set up 301 redirects for hundreds of posts.

I guess there's probably a way of using the model() method but making the url show as the slug, but I'm not at that level yet!

**Comment by MurhafSousli** [comment]
@markgoho There are many websites which use the Id, and still have good SEO, (e.g. microsoft website links), but if you are worried about it, go for the slug it will work perfectly. but for mobile apps URL is not needed therefore Id should be the way to go.
I'm also making a wp [starter-theme](https://github.com/MurhafSousli/ng-wordpress-theme). I'm looking for collaborators like you to improve it.
