### ISSUE TITLE
Retrieve categories in heirarchy

### ISSUE THREAD

**Issue by markgoho** [MurhafSousli/ng2-wp-api#13]
It would be great to be able to get a Categories collection with children categories already in the parent objects.

Right now, you can filter the Category array by .parent === 0 to get the "parent" categories, but there's no easy way to match up all the children categories to their parents.

On wordpress sites, there's a pretty standard category widget that you can drop in with a "Show hierarchy" option. I can imagine this is something that a lot of people will want to do with the api, and thus with this library.

**Comment by MurhafSousli** [comment]
@markgoho That's true, you should get all categories and then create a JSON tree corresponding to the `parent` field, I add this function in the next version.
another way is to extend the response from WordPress (by writing a plugin)

**Comment by markgoho** [comment]
Yeah, it's like I know what should be done, but don't have the chops to
actually code it out. I'm glad this functionality will be in the next
release! Thank you!

**Comment by MurhafSousli** [comment]
@markgoho  Can you contribute on this, find a js function that has an input for category json data, and return a new tree where child categories are included under parent categories (recursively if possible) and I will integrate it in our module, it isn't complicated but I can't find the time to work on this.

**Comment by markgoho** [comment]
I can certainly try! I was actually about to sit and work on this this week
(assuming I didn't see something from you).

**Comment by MurhafSousli** [comment]
@markgoho I didn't forget, but I'm overloaded with couple of modules, I'm focusing on the features I need  at work

**Comment by markgoho** [comment]
Absolutely! This would be nice to have, but definitely not a core feature.
I'm on it :)
