### ISSUE TITLE
Fix AoT error

### ISSUE THREAD

**Issue by MurhafSousli** [MurhafSousli/ng2-wp-api#17]

**Comment by markgoho** [comment]
I've built for production with AoT and I'm not getting any errors. Any details on this?

**Comment by MurhafSousli** [comment]
@markgoho Are you using `WordPressModule.forRoot('http://adasd.com')` ?

**Comment by markgoho** [comment]
@MurhafSousli Ahh, no--I'm just importing WordPressModule
