### ISSUE TITLE
Broken in 3.0.0-beta1: WpQueryArgs no longer exported

### ISSUE THREAD

**Issue by markgoho** [MurhafSousli/ng2-wp-api#18]
`"export 'WpQueryArgs' was not found in 'ng2-wp-api'`

This seems like a breaking change but isn't listed in the changelog. I also don't see it referenced in the readme.

**Comment by MurhafSousli** [comment]
@markgoho `WpQueryArgs` is removed! I think I forgot to remove it from the changlelog, args should be passed as an object
```
args = {
   _embed: true,
  per_page: 5
}
```
and so on
