### ISSUE TITLE
Broken in 3.0.0-beta1: link no longer a method

### ISSUE THREAD

**Issue by markgoho** [MurhafSousli/ng2-wp-api#19]
`Property 'link' does not exist on type 'WpService'.`

E.g. `this.services$ = this.wpService.link('https://www.gideonlabs.com/wp-json/wp/v2/pages?per_page=30&parent=65');`

This is broken in 3.0.0-beta1

**Comment by MurhafSousli** [comment]
Direct link was meant for external services such as any http request, the only reason I added it is to get the advantage the `loading` and `errors` notifiers introduced in `2.x` but after they are removed in 3.x, direct links through this module won't make any difference and they are out of the module scope, things will be clearer in the future updates
