### ISSUE TITLE
Problem include in app.module

### ISSUE THREAD

**Issue by cguagenti** [MurhafSousli/ng2-wp-api#2]
Hi, I updated Angular CLI to latest beta version.

I created a empty project, installed package with command: `npm install ng2-wp-api --save` but when I add this `import { WordPressModule } from 'ng2-wp-api/dist';` on my app.module the page freeze.

**Here the error:** 

metadata_resolver.js:227 Uncaught Error: Unexpected value 'e' imported by the module 'AppModule'

**My information:**
`ng --version`
angular-cli: 1.0.0-beta.16
node: 6.6.0
os: win32 x64

Do you know if I wrong something? Sorry for my English! Thanks!

**Comment by MurhafSousli** [comment]
Hi @calogeroguagenti, I just tested it now on a new empty project using the CLI and I couldn't get an error

![capture](https://cloud.githubusercontent.com/assets/8130692/19055870/dfcde98c-89ce-11e6-8add-2505dc1f83a9.PNG)

Try to create a new empty project and install the plugin again, If you still get the same error, then download the source code and import `WordPressModule` from the `src` directory.

**Comment by cguagenti** [comment]
Hi @MurhafSousli, thanks for rapid answer. Which version do you have of angular cli? Is 1.0.0-beta.16?

cheers

**Comment by MurhafSousli** [comment]
@calogeroguagenti yupp I'm using the latest version 1.0.0-beta.16

**Comment by cguagenti** [comment]
Tested in a empty project and works fine. Thank you
