### ISSUE TITLE
Cannot invoke an expression whose type lacks a call signature.

### ISSUE THREAD

**Issue by markgoho** [MurhafSousli/ng2-wp-api#20]
![image](https://cloud.githubusercontent.com/assets/9759954/23476824/fef5c958-fe89-11e6-8969-f54ab5726e52.png)

Getting the error on this:
`ERROR in C:/Users/Jack/Documents/GitHub/gideonLabs/src/app/posts/post-single/post-single.component.ts (36,5): Cannot invoke an expression whose type lacks a call signature.)`

**Comment by markgoho** [comment]
This has something to do with dot chaining.

This works:
```
this.collection = this.wpService.collection().posts();
    this.collection.get({ slug: this.slug })
      .subscribe((res: CollectionResponse) => {
        if (res.error) {
          console.log(res.error)
        } else {
          this.post = new WpPost(res.data[0]);
        }
      });
```

This does _not_ work:
```
this.wpService.collection().posts().get({ slug: this.slug })
      .subscribe((res: CollectionResponse) => {
        if (res.error) {
          console.log(res.error)
        } else {
          this.post = new WpPost(res.data[0]);
        }
      });
```

**Comment by MurhafSousli** [comment]
by the time I investigate, I recommend you to explore the directives, better performance and less code, they are awesome
```ts
<div class="single-post" [wpCollection]="endpoint" [wpArgs]="{slug: slug, _embed: true}" (wpResponse)="response($event)">
  <h1 [innerHtml]="single?.title()"></h1>
</div>

endpoint = WpEndpoint.posts;
single;
response(res){
   if(res.data && res.data.length){
      this.single = new WpPost(res.data[0]);
   }
}
```

**Comment by markgoho** [comment]
I'll give them a shot. I'm new to angular and I feel a lot more comfortable
with services. But this may the motivation I need to get more familiar with
directives!

**Comment by MurhafSousli** [comment]
It seems to work now
