### ISSUE TITLE
How to retrieve a posts list from a specific post type?

### ISSUE THREAD

**Issue by danillobarbosa** [MurhafSousli/ng2-wp-api#25]
How to specify the type of post we want in the collection?

**Comment by MurhafSousli** [comment]
@danillobarbosa To get the official post types, we use the endpoints `post`, `page`, `categories`, `projects`.. etc

```ts
<div class="post" [wpCollection]="endpoint" [wpArgs]="args" (wpResponse)="response($event)">
</div>
```
```ts
endpoint = WpEndpoint.posts;  //  returns '/wp-json/wp/v2/posts/'
// or a custom post endpoint
// endpoint = '/wp-json/wp/v2/projects/';
```
if your post type is not registered to a custom endpoint in the API, you can use wp query arguments, (needs to have the [filter plugin](https://github.com/WP-API/rest-filter))
```ts
args = {
  filter: {
     post_type: 'post'
  }  
}
```
