### ISSUE TITLE
Can't bind to 'wpModel' and 'wpId"

### ISSUE THREAD

**Issue by markgoho** [MurhafSousli/ng2-wp-api#28]
Using the docs to try and pull in a single page by id, getting the following errors.

```
Can't bind to 'wpModel' since it isn't a known property of 'div'. ("
    <div class="single-post" [ERROR ->][wpModel]="postsEndpoint" [wpId]="10" (wpResponse)="single = $event.data">
Can't bind to 'wpId' since it isn't a known property of 'div'. ("
    <div class="single-post" [wpModel]="postsEndpoint" [ERROR ->][wpId]="10" (wpResponse)="single = $event.data">
```

**Comment by markgoho** [comment]
In a brand new project with just ng2-wp-api imported, this is working properly. Is it possible some other module is causing this error?

**Comment by markgoho** [comment]
Could be an issue with trying to use it in a feature module. What's the syntax for importing WordPressModule in a feature module?

**Comment by MurhafSousli** [comment]
@markgoho I think your component belongs to a child module, add `WordPressModule` to that module (without forRoot this time), I added this to docs usage
