### ISSUE TITLE
Issue on Filter

### ISSUE THREAD

**Issue by cguagenti** [MurhafSousli/ng2-wp-api#3]
Thanks for this wonderful package! I found some issue.

An example: I need to select a post with from a slug.

The endpoint is: /wp-json/wp/v2/posts/?filter[name]=my-slug-post

**Problem 1**
I can't pass the `name` param inside the `filter` (_filter[name]_)

**Problem 2**
I cant't make a request with only filter param, but I need to pass an ID like this:
/wp-json/wp/v2/posts/**{ID}**?filter[name]=my-slug-post

Thanks for the good work

**Comment by MurhafSousli** [comment]
Hi @calogeroguagenti 

**Problem 1:** You just need to initialize `args.filter = {}` to be able to use `args.filter['name']=slug`

``` javascript
  args = new WpQueryArgs({
    filter: {
        name: this.slug
    }
  });
//or  
 args = new WpQueryArgs({
    filter: {}
  });
args.filter['name'] = this.slug;
```

**Problem 2:** It makes no sense to get a post by ID, and filter it by post slug, right!

Maybe you misunderstood something, there is two built in services in `WpService`

1 - `WpService.collection()`: and here `filter` and other `parameters` can be useful, if you want to get a post by slug, then use this one `filter['name']=postSlug` (you can't pass the Id with this service).

2 - `WpService.model()`: to get something by Id, in this service the only useful parameter in `WpQueryArgs` would be `args._embed = true` or `args.filter['_embed'] = true` where it returns the embedded post. other parameters won't effect the response.

**Comment by cguagenti** [comment]
You're right! Thank you too much!!
