### ISSUE TITLE
Can you point to more example code?

### ISSUE THREAD

**Issue by davetbo** [MurhafSousli/ng2-wp-api#35]
Hello,

As far as I can tell, this appears to be the only Wordpress API client for Angular4.  Thanks for providing this great functionality.

I'm brand new to Angular and TypeScript.  Can you provide an example of how to use your library to authenticate with Wordpress and execute a query for a list of posts?  I know you have some brief examples in your documentation, but being new to Angular, they're too disconnected for me to piece them together into a working example.

I really appreciate your advice.

Best,
Dave

**Comment by MurhafSousli** [comment]
Hi @davetbo, I have already put simple examples and advanced examples.
I suggest you read the docs step by step, try the simple examples, if it did not work, then open an issue describe what you are trying to do and include your usage of the module and I will help you if I can.

Here is the simplest straight forward example I can give:

 - Generate a new empty project using [Angular CLI](https://github.com/angular/angular-cli)
-  Install the module `npm install --save ngx-wordpress`
 - Go to the root module `app.module.ts` and import `WordPressModule`
```ts
import { WordPressModule } from 'ngx-wordpress';
@NgModule({
imports: [
    // ...
    WordPressModule.forRoot('https://example.com') //address to your WordPress site
  ]
})
```
 - Go to app template `app.component.html` and add the following:
```html
<ul wpCollection="posts" [wpArgs]="{ }" (wpResponse)="res = $event">

   <li *ngFor="let post of res?.data"> {{ post.title.rendered }} </li>

</ul>
```
You should see your WordPress posts titles now

**Comment by Jscott388** [comment]
This does not work.  No definition found for res:
`   <li *ngFor="let post of res.data"> {{ post.title.rendered }} </li>
`
Should there be something done in the component?

**Comment by MurhafSousli** [comment]
@Jscott388 Nope, you don't need to do anything from the component.
Add `?`  here `res?.data`
Look I just tested the example now

![test](https://cloud.githubusercontent.com/assets/8130692/26280363/38c5c316-3dd9-11e7-8064-24e64597301d.gif)
