### ISSUE TITLE
Array of posts using WpPost class

### ISSUE THREAD

**Issue by Jscott388** [MurhafSousli/ng2-wp-api#36]
Running a mind blank here, but what if I want to have a post listing component that has a list of tags in it as well. How would I run the loop to display those? 

For example: 
`<md-card *ngFor="let post of posts">
  <md-card-title-group>
    <md-card-title>
      <h4>{{post.title.rendered}}</h4>
    </md-card-title>
    <md-card-subtitle>
      <h5>{{ post.date }}</h5>
    </md-card-subtitle>
    <img *ngIf="post.featured_media" md-card-sm-image [src]="post._embedded['wp:featuredmedia'][0].media_details.sizes.medium?.source_url">
  </md-card-title-group>
  <md-card-content>
    <p [innerHTML]="post.excerpt.rendered"></p>
  </md-card-content>
  <md-card-actions>
    <button md-raised-button [routerLink]="[post.slug]">Read More</button>
  </md-card-actions>
  <md-card-footer>
    <md-chip-list>
      ------ TAGS HERE -------
    </md-chip-list>
  </md-card-footer>
</md-card>`

Was going to use a chip here to handle the tags.

Now I get you can use the WpPost Class in the single post. post.tags(), however I get nothing back in a single post where I am using the WpPost Class. Also no author() and categories() return nothing. Using {{ post.author() | json }}, same for categories and tags. No json data.

Thanks.

**Comment by MurhafSousli** [comment]
@Jscott388 When you use **[WpPost](https://github.com/MurhafSousli/ngx-wordpress/wiki/WpPost-class)**, all post properties are accessed using the functions.
First create a child component, let's say `<post-item>` and in its template

```html
<md-card *ngIf="post">
    <md-card-title-group>
        <md-card-title>
            <h4>{{ post.title() }}</h4>
        </md-card-title>
        <md-card-subtitle>
            <h5>{{ post.date() }}</h5>
        </md-card-subtitle>
        <img *ngIf="post.featuredMedia()" [src]="post.featuredImage('large')">
    </md-card-title-group>
    <md-card-content>
        <p [innerHTML]="post.excerpt()"></p>
    </md-card-content>
    <md-card-actions>
        <button md-raised-button [routerLink]="['./', post.slug()]">Read More</button>
    </md-card-actions>
    <md-card-footer>
        <md-chip-list *ngFor="let tag of post.tags()">{{ tag.name }}</md-chip-list>
    </md-card-footer>
</md-card>
```
```ts
export class PostItemComponent{
  post: WpPost;

  @Input() set data(data) {
    // create WpPost from data
    this.post = new WpPost(data);
  }
}
```

In parent component
```html
<div wpCollection="posts" [wpArgs]="args"
          (wpResponse)="onWpResponse($event)" (wpLoading)="loading = $event">

    <post-item *ngFor="let post of posts" [data]="post"></post-item>
</div>

<md-spinner *ngIf="loading"></md-spinner>
<button md-raised-button (click)="more()">Load More Posts</button>
```

```ts

 posts;
 args = {
    per_page: 5,  //get 5 items per page
    _embed: true  //enable featured image, categores, tags and author in the response
 };

 /** Handle WP Response */
 onWpResponse(res) {
    if (res) {
      if (res.error) {
        console.log('[WP posts response]:', res.error);
      }
      if(!res.data.length){
        console.log('[WP posts response]: Empty response!');
      }
      if (res.data) {
        this.posts = res.data;
      }
    }

  @ViewChild(CollectionDirective) wpCollection;  
  /** 
  *  Use the directive reference to call functions like `next()` `prev()` for pagination 
  *  or `more()` for loading more
  */  
   more() {
      this.wpCollection.more();
   }
 }
```

**Comment by Jscott388** [comment]
@MurhafSousli Thanks! Do you have a full fledged working example site that I could reference too? I would like to see it more in action than just code samples. I would love to help the wiki out in actually making a start from finish tutorial. Just getting my head around Angular 4 and how everything works.

**Comment by MurhafSousli** [comment]
@Jscott388  I would have made a demo, but github pages requires a secured wordpress url (https) and mine is `http`, if you have a secured one already and you don't mind sharing it, I can make a demo using your wp backend
And sure It would be great if someone can help me improving the wiki

**Comment by Jscott388** [comment]
Have nothing in a repo? Don't need a live working one, just general layout.

**Comment by MurhafSousli** [comment]
Unfortunately I don't have one
