### ISSUE TITLE
TypeError: t.prototype.get.call(...).timeout is not a function

### ISSUE THREAD

**Issue by cguagenti** [MurhafSousli/ng2-wp-api#4]
I updated npm, node and ng2-wp-api on the last versions.

If I try to serve the app I get this error. Issue or my fault?

Thanks as always

![screen-error](https://cloud.githubusercontent.com/assets/1781058/19308867/bd05c076-9079-11e6-9726-993241b0c763.png)

**Comment by MurhafSousli** [comment]
Try to add this `import 'rxjs/add/operator/timeout';` in your root module and let me know if it works, if not, add the whole library `import "rxjs";` in your root module, I will fix this next release, The problem with `timeout` operator that I can't add it alone like `import "rxjs/add/operators/timout"`, we have to load the whole library just for this operator, I will investigate this issue with the angular group

**Comment by cguagenti** [comment]
Ok, I will let you know in the morning. Thanks!

**Comment by MurhafSousli** [comment]
@calogeroguagenti It's fixed now, I have pushed the updates to npm. 
by the way you might be interested to use `ng-progressbar` which works pretty well with the loading notifier and also the share buttons
https://github.com/MurhafSousli/ng2-progressbar/
https://github.com/MurhafSousli/ng2-sharebuttons/

**Comment by cguagenti** [comment]
Thank you. Very kind.
