### ISSUE TITLE
Angular 7 support

### ISSUE THREAD

**Issue by CrayFlatline** [MurhafSousli/ng2-wp-api#48]
I'm newbee and I'm trying to use your great package with Ionic Conference App (latest). 
When I try to add it I got

npm i -S @ngx-wordpress/core
npm WARN @ngx-wordpress/core@5.0.0-beta.6 requires a peer of @angular/common@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngx-wordpress/core@5.0.0-beta.6 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.

But in app package.json I have

    "@angular/common": "7.1.4",
    "@angular/core": "7.1.4",

What is wrong? :)

**Comment by MurhafSousli** [comment]
This is just a warning, there is no problem with the package :)

**Comment by CrayFlatline** [comment]
Thanks a lot!
