### ISSUE TITLE
ERROR in node_modules

### ISSUE THREAD

**Issue by matuskrizo** [MurhafSousli/ng2-wp-api#49]
Hi, great work man. :)

After ng serve I've got an error:
ERROR in node_modules/@ngx-wordpress/core/lib/wordpress.service.d.ts(27,12): error TS2307: Cannot find module '../../../../../../../../../Users/Murhaf/Desktop/Github/ngx-wordpress/node_modules/rxjs/internal/Observable'.

**Comment by sampow** [comment]
@matuskrizo, until @MurhafSousli  have time to fix it you can : replace in  node_modules/@ngx-wordpress/core/lib/wordpress.service.d.ts : line 27
`'../../../../../../../../../Users/Murhaf/Desktop/Github/ngx-wordpress/node_modules/rxjs/internal/Observable'.`
by
`    error: import("../../../rxjs/internal/Observable").Observable<Error>;
`

**Comment by bh-adrienne** [comment]
This should be a pull request, not a closed issue.
