### ISSUE TITLE
Unexpected value 'e' - WordPressModule

### ISSUE THREAD

**Issue by Soean** [MurhafSousli/ng2-wp-api#5]
When I add the WordPressModule to NgModule imports array, I get the following error in the chrome web console.

`Error: Unexpected value 'e' declared by the module 'AppModule'`

I used the Ng CLI and just added the module.

**Comment by Soean** [comment]
I found #2 with the same problem. I tried it again with an empty project and got the same issue.

ng --version
angular-cli: 1.0.0-beta.17
node: 6.8.0
os: darwin x64

**Comment by MurhafSousli** [comment]
@Soean Try to `import WordPressModule from "ng2-wp-api/dist"`, or  `import WordPressModule from "ng2-wp-api/dist/index"` let me know if it solved the problem

**Comment by Soean** [comment]
`import { WordPressModule } from 'ng2-wp-api/dist';`
`import { WordPressModule } from 'ng2-wp-api/dist/index';`
Nothing changed, same problem.

If I import without curly braces:
`import WordPressModule from "ng2-wp-api/dist";`
Module '".../node_modules/ng2-wp-api/dist/index"' has no default export.

**Comment by MurhafSousli** [comment]
@Soean use the source code for now, the error is happening when I push it to npm... I'm working on it,

**Comment by MurhafSousli** [comment]
@Soean it should work now, please download it again

**Comment by Soean** [comment]
Thanks for your fast answer and commit. Now it works :) !
