### ISSUE TITLE
Token not getting set in the browser local storage

### ISSUE THREAD

**Issue by dapojaja** [MurhafSousli/ng2-wp-api#50]
Token is not getting set in browser storage. Hence immediately after auth.signIn..., i get from the browser console 

`zone.js:3243 GET http://localhost/wp/wp-json/wp/v2/users/me 401 (Unauthorized)`

and after doing a

`this.auth.signIn(login.name, login.password).subscribe(res => console.log(JSON.stringify(res)));`

i get

`{"user":null,"loading":false,"loggedIn":false,"error":{"code":"rest_not_logged_in","message":"You are not currently logged in.","data":{"status":401}}}`

please i do i get token "set"?

i'm using chrome 65
Thanks

**Comment by MurhafSousli** [comment]
It will only be saved if you authenticate successfully, it is by design https://github.com/MurhafSousli/ngx-wordpress/blob/master/projects/core/src/lib/auth/wp-auth-ref.ts#L72

**Comment by dapojaja** [comment]
Thanks very much for your response. I do authenticate correctly.  
Intentionally authenticating with wrong login detail bring the following

```
/wp/wp-json/jwt-auth/v1/token:1 POST http://localhost/wp/wp-json/jwt-auth/v1/token 403 (Forbidden)
app.component.ts:31 {"user":null,"loading":false,"loggedIn":false,"error":{"code":"[jwt_auth] invalid_username","message":"<strong>ERROR</strong>: Invalid username. <a href=\"http://localhost/wp/wp-login.php?action=lostpassword\">Lost your password?</a>","data":{"status":403}}}
```

Rightly authenticating generates the following:

```
GET http://localhost/wp/wp-json/wp/v2/users/me 401 (Unauthorized)
app.component.ts:31 {"user":null,"loading":false,"loggedIn":false,"error":{"code":"rest_not_logged_in","message":"You are not currently logged in.","data":{"status":401}}}
```

Authenticating using Postman 

```
`http://localhost/wp/wp-json/jwt-auth/v1/token?username=dapz&password=qwe`

brings:

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3RcL3dwIiwiaWF0IjoxNTU5NjAyMTM3LCJuYmYiOjE1NTk2MDIxMzcsImV4cCI6MTU2MDIwNjkzNywiZGF0YSI6eyJ1c2VyIjp7ImlkIjoiMiJ9fX0.TVqvPrq8K_s407GMpchnuPyHRhk2GmfkVy_ZO_x3ZkM",
    "user_email": "dapz@gmail.com",
    "user_nicename": "dapz",
    "user_display_name": "dapz dapz"
}
```
Please what else can I do?

Thanks

Dapo

**Comment by MurhafSousli** [comment]
Can you test it out with the repository demo?

**Comment by dapojaja** [comment]
How do I test out with the repository demo?, the https://stackblitz.com/edit/ngx-wordpress not working.

These are snapshots.

Image1: Auth with correct username and password
![ngx wp issue 2](https://user-images.githubusercontent.com/32075631/58856680-36442800-869b-11e9-8bf7-d4778b49e04b.jpg)

Image2: Auth with incorrect password
![ngx wp issue 3](https://user-images.githubusercontent.com/32075631/58856681-36442800-869b-11e9-8e0a-977f5ead41c0.jpg)

Image3: Auth with correct username and password using Postman
![ngx wp issue 1](https://user-images.githubusercontent.com/32075631/58856682-36dcbe80-869b-11e9-85a1-e24af7600ce1.jpg)

Thanks for taking out time to respond.

**Comment by MurhafSousli** [comment]
No there is no stacbklitz, I mean about the demo app in the repo https://github.com/MurhafSousli/ngx-wordpress/tree/master/src/app

Did you install the [required auth plugins](https://github.com/MurhafSousli/ngx-wordpress/wiki/Authentication)?

**Comment by dapojaja** [comment]
I'm sorry the for the long silence. From the demo, after changing the default baseUrl to 'http://localhost/wp', and signing in, it actually created the token and immediately it disappears while inspecting in Chrome. screen record at https://drive.google.com/file/d/1SQgn6dBIFjVkCTak65aJiZAGepmShrc7/view?usp=sharing

Thank you

**Comment by dapojaja** [comment]
I just find out that the issue is only on my localhost. Is there anything i can do to get it working? Authenticating directly work as well as thru postman. Thanks.

**Comment by dapojaja** [comment]
Do I have to configure ssl on localhost? Thanks

**Comment by MurhafSousli** [comment]
I really have no clue.

**Comment by dapojaja** [comment]
Thanks for the attention. I'll keep looking for the solution. If i'm successful, i'll definitely post it here.

**Comment by dapojaja** [comment]
Afetr jumping though many websites, eventually got it working on my localhost by enabling ssl on my localhost. Best straight forward solution here https://ssl.indexnl.com. Thank you for the wonderful module.
