### ISSUE TITLE
Unit and End tests - Ionic extention ?

### ISSUE THREAD

**Issue by 3kynox** [MurhafSousli/ng2-wp-api#6]
Hello and thanks for this project that looks great, I was looking for something simple to communicate with a wordpress installation with apiv2 plugin on it, where there is some projects over github, your one looks sexy.

My questions are : 
- Any plan to extend functionalities to do unit and end tests ? (using karma / jasmine / protractor)
- Any plans to provide ionic extention to build apk / ios packages based on web version ? Something similar than https://github.com/shprink/wordpress-hybrid-client finally.

Thanks for the answers.

**Comment by MurhafSousli** [comment]
Hi @3kynox, yes I have plan to do unit and end tests as soon as I get free time.
for the second question, it is definitely a good idea for a new project, but this one is just an angular2 module not a starter, if you got angular2 ionic2 starter, this package will work for your apps.

**Comment by 3kynox** [comment]
Hello again,

I just realized I was on https://github.com/MurhafSousli/ng2-wordpress-theme repository at first because I was checking a WP API v2 / Angular 2 solution (or theme) but here this is about the module.

Does the theme use this module ? I feel a little lost maybe ;)

**Comment by MurhafSousli** [comment]
@3kynox No that one is pretty old, but I also have plan to write it again from scratch
