### ISSUE TITLE
Allow non standard url prefix

### ISSUE THREAD

**Issue by enricodeleo** [MurhafSousli/ng2-wp-api#7]
Some developer doesn't use standard `wp-json` basepath as well as he use different namespaces for custom endpoints. 
Do you have any plan of implementing methods for these scenarios? 

I [contributed to the woocommerce node api client in such a way](https://github.com/woocommerce/wc-api-node/pull/24) , I would suggest the same thing here.

**Comment by MurhafSousli** [comment]
Hi @enricodeleo, `wp-json` part is in the default endpoints [`WpEndpoint`](https://github.com/MurhafSousli/ng2-wp-api/blob/master/src/helpers/wp-endpoints.ts), not in the base path.
You can access custom routes with the endpoint function like this:

```javascript
//collection
this.wpService.collection().endpoint('wp-rest/wc/v1/foo').get(args).subscribe(...)
//model
this.wpService.model().endpoint('wp-rest/wc/v1/foo').get(id, args).subscribe(...)
``` 
or using components
```html
<wp-model [id]="id" [endpoint]="'wp-rest/wc/v1/foo'" (response)="wpResponse($event)">
<!-- Your Template Goes Here -->
<wp-model>

<wp-collection [args]="args" [endpoint]="'wp-rest/wc/v1/foo'" (response)="wpResponse($event)">
<!-- Your Template Goes Here -->
</wp-collection>
```

**Comment by enricodeleo** [comment]
@MurhafSousli thank you for your reply. Yes, I'm actually do what you're suggesting, I just thought that if url prefix were customizable the code would be less verbose and you could also use built-in helpers.

**Comment by MurhafSousli** [comment]
@enricodeleo What about users who would use multiple plugins endpoints.
 e.g. if the developer set the `wpAPI` and `version` to a custom endpoint, then they won't be able to use the default one anymore, the library has only one main service that should serve default and custom endpoints.

**Comment by enricodeleo** [comment]
I'm not talking about `version`, neither about `namespace`, I'm just referring to the url prefix (default is `wp-json`) that in some case is a custom one (eg when wp-api v1 and v2 coexist).

If you filter the url prefix with something like 

```php
add_filter( 'rest_url_prefix', function () { return 'wp-api'; } );
```

you get `mydomain.ext/wp-api/wp/v2`, `mydomain.ext/wp-api/wc/v1` etc... Since it is a constant I think it would be reasonable not to repeat in every `.endpoint()` call.
