### ISSUE TITLE
Not able use in my application

### ISSUE THREAD

**Issue by suryadev-singh** [MurhafSousli/ng2-wp-api#8]
**Error : ng2-progressbar not found**

I have follow this step  -
1) - I have install in node_modules using given command : 
 2) - define in system.config.js as : 
           map:   {
               'ng2-progressbar': 'npm:ng2-progressbar
             }
 3)- importing in app.module.ts as : 
        import  { NgProgressModule } from "ng2-progressbar";
       @NgModule({
                 imports:      [NgProgressModule],
                 declarations: [  ],
                 bootstrap:    [  ]
           })
4)- Importing in  app.component.ts  as : 
import {NgProgressService} from "ng2-progressbar";
@Component({
  selector: 'my-app',
  template: `<ng-progress></ng-progress> <h1>Hello {{name}}</h1>`
})
export class AppComponent  {
    name = 'Angular delhi';
    constructor(private pService: NgProgressService) {
  }

  ngOnInit(){
      /** request started */
      this.pService.start();
      this.http.get('abc.com').subscribe(res){
          /** request completed */
          this.pService.done();
      }
  }
}   
  
Then Error  in console ------ :

 GET http://localhost:3000/node_modules/ng2-progressbar/ 404 (Not Found)  zone.js:1645

 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/node_modules/ng2-progressbar(…)   (index):16

**Comment by MurhafSousli** [comment]
Hi @suryadev-singh, This is not ng2-progressbar repo, please open the issue in [here](https://github.com/MurhafSousli/ng2-progressbar/issues)
