### ISSUE TITLE
zone.js:388 Unhandled Promise rejection: (SystemJS) XHR error (404 Not Found) loading http://localhost:8009/ng2-progressbar

### ISSUE THREAD

**Issue by andeoliveira** [MurhafSousli/ng2-wp-api#9]
I am not able to configure ng-
progressbar, is there any additional configuration to do in system.js?
![err](https://cloud.githubusercontent.com/assets/4259936/22151253/8801e7b8-df04-11e6-9600-c5f2e2c1961d.png)

**Comment by MurhafSousli** [comment]
Hi @andherrson, this is not `ng2-progressbar` repo, please reopen your issue [here](https://github.com/MurhafSousli/ng2-progressbar/issues)
